### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by silviucpp** [lpgauth/buoy#1]
Hello I was wonder if in `buoy_client` line 64 is not :

``` erl
{ok, [{request_id(RequestsIn), Response}], State#state
```

instead :

``` erl
{ok, [{RequestsIn, Response}], State#state
```

Otherwise I cannot see how `RequestId` from `handle_request` can match correctly the response.

Silviu

**Comment by lpgauth** [comment]
Hi @silviucpp,
I just released version `0.1.0`. Any bugs you experienced using the very alpha version should be fixed.

Cheers,
LP
