### ISSUE TITLE
Some performance issue

### ISSUE THREAD

**Issue by silviucpp** [lpgauth/buoy#15]
Hello,

Basically in our flow we are sending very large body's in the requests (we are buffering lot of events and send them bulk via a single http call to one of our services). Buoy is great but we noticed at least a theoretical issue:

We are using the async interface and in the message that we receive as response, request is included as well which means very huge binaries are still referenced so they still reside in memory and are not released once they were sent to the server.

Do you think it's possible to set some option and to not include the request in the response message?

Silviu

**Comment by lpgauth** [comment]
Hi @silviucpp,
I will see what I can do. This functionality is abstracted away by shackle, so I'll have to patch it there.

I'll keep this ticket updated when I have news.

**Comment by lpgauth** [comment]
Fixed by https://github.com/lpgauth/buoy/pull/21.

**Comment by silviucpp** [comment]
I see now you removed the entire request record. If you have multiple pools to multiple hosts is hard to know what host failed... Before we used the server information from request record.

**Comment by lpgauth** [comment]
You can get the pool used by checking the ReqID. The first element of the tuple is the server that handled the requests.

https://github.com/lpgauth/shackle/blob/master/include/shackle.hrl#L5
