### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by 9mm** [lpgauth/buoy#26]
This might be a silly question, but what does "concurrent requests per connection" mean? I thought HTTP/1.1 was only 1 request at a time over a keep-alive connection?

**Comment by lpgauth** [comment]
Hi @9mm, Buoy supports HTTP pipelining (https://en.wikipedia.org/wiki/HTTP_pipelining).

**Comment by 9mm** [comment]
Oh damn, I didn't know about this. Is this common? I feel retarded for never hearing about this.

I'm facing a problem where I need to connect to 5 different XML HTTP APIs and make about 20,000 requests per minute on each one (so about 100,000 requests/min total).

The problem is they don't support HTTP/2 so I've been struggling with how to hit this level of performance, then I found your library so I'm going to give it a shot.

I know that they are all mostly running Apache 2.2+, there might be some running nginx but I can't tell because the server header is removed. I'm not sure if those support pipelining

**Comment by 9mm** [comment]
So one other thing I'm thinking of, it says `pool_strategy` is round robin/random.

How does the same pool handle multiple connections to different hosts?

**EDIT** Actually I see you pass the URL to the pool, so it must be for that host only. If I close a pool does it wait until current connections are done or does it destroy the current pending requests immediately?

**Comment by 9mm** [comment]
In other words, can I create pools and close them on the fly easily, or must I keep track of connections currently open before closing etc.

The problem is that I have ~5-10 URLs I need to hit very much, but occassionally the list will change. so every minute I need to re-assess what hosts I'm hitting, and i need to create/destroy pools accordingly for each host

**Comment by 9mm** [comment]
Sorry for all the messages. I will just consolidate everything into a few bullet points from my last few days of working with buoy. These are easy questions but I'm new to elixir, and don't know any erlang, so it's hard for me to read the source.

1. if I `:buoy_pool.stop(url)` on a pool, does it close all the connections gracefully? My challenge is I need to do a lot of different URLs and it is hard to keep track of pools for every URL.

2. When I add the request timeout of `500` it seems to hang/crash elixir. I know you probably dont really work with elixir but I was wondering if you knew what that might be from?

3. What happens if you add a request to a pool and the pool is full. Does it queue it nicely and do it when it can or does it raise an exception?

4. How come it fails with any SSL host when creating a pool? `[:"https_httpbin.org_443"] connect error: :timeout`

5. Why does the path matter when setting a pool? I am going to hit a URL many times but the query parameters change, but its making me create a new pool for each one, even if ?x=y becomes ?x=3

6. What does `no_socket` mean? It will be connecting find and then randomly throws this error?

**Comment by 9mm** [comment]
I'm going to close this so its not overwhelming amount of questions. I really just have 1 main question, and that is... whats the best way to use buoy when I don't know the URL before hand? In other words, I cant manually create a pool ahead of time. Is it bad if i attempt to start a pool before every single request?
